function A_ref = lrprop(profile, prop)
% LRPROP - Main Longley-Rice propagation calculation routine.
%
% This function calculates the reference attenuation (A_ref) by determining
% the propagation mode (Line-of-Sight, Diffraction, or Scatter) and
% calling the appropriate sub-function to compute the loss.
%
% SYNTAX:
%   A_ref = lrprop(profile, prop)
%
% INPUTS:
%   profile - The terrain profile structure from read_terrain().
%   prop    - The comprehensive properties structure generated by qlrpfl.
%
% OUTPUTS:
%   A_ref - The reference attenuation in dB, relative to free-space loss.
%
% See also: alos, adiff, ascat.

    % --- Constants ---
    R_a = 6371000; % Earth's radius in meters
    
    % --- Extract necessary parameters from prop structure ---
    d_km = prop.d_km;
    he1 = prop.he(1);
    he2 = prop.he(2);
    the1 = prop.the(1);
    the2 = prop.the(2);
    
    % --- Calculate effective earth radius and curvature ---
    gamma_a = 1 / R_a;
    N1 = 179.3; 
    gamma_e = gamma_a * (1 - 0.04665 * exp(-prop.N_s / N1));
    a_e = 1 / gamma_e;

    % --- Calculate smooth-earth horizon distances ---
    % These are the distances to the horizon over a perfectly smooth sphere.
    d_ls1 = sqrt(2 * a_e * he1);
    d_ls2 = sqrt(2 * a_e * he2);
    d_los_smooth = d_ls1 + d_ls2;
    
    % --- Determine Propagation Regime ---
    
    % The primary check is based on the horizon elevation angles. If both
    % antennas clear all obstacles, the path is considered Line-of-Sight.
    % The horizon distances (dl) from hzns tell us where the obstacles are.
    % A simple check is if the path distance is less than the sum of the
    % horizon distances.
    
    is_los = (d_km * 1000) <= (prop.dl(1) + prop.dl(2));

    if is_los
        % --- Line-of-Sight (LOS) Regime ---
        %disp('Propagation Mode: Line-of-Sight');
        A_ref = itm.alos(profile, prop);
        
    else
        % --- Trans-Horizon (Diffraction or Scatter) Regime ---
        
        % Calculate Diffraction Loss
        %disp('Propagation Mode: Diffraction');
        A_diff = itm.adiff(profile, prop);
        
        % Calculate Scatter Loss
        %disp('Propagation Mode: Scatter');
        A_scat = itm.ascat(prop);
        
        % The diffraction-scatter crossover distance (dx) is where the two
        % models predict the same loss. The model blends these two values.
        % A full implementation would calculate dx and perform a smooth
        % blending. For now, we will use the diffraction loss as the primary
        % trans-horizon mechanism, as scatter is dominant only at very
        % great distances not typical for this profile.
        
        if A_diff < A_scat
            A_ref = A_diff;
        else
            A_ref = A_scat;
        end
    end
end
